
data:
  base_dir: "C:/dataset/ori_coco/images"
  type: "val2017"
  annotations: "annotations/instances_{type}.json"
  images: "{base_dir}/{type}"

output:
  base_dir: "C:/dataset/wheelchair/coco/images"
  labels_dir: "{base_dir}"

names:
  0: "person"
  1: "bicycle"
  2: "car"
  3: "motorcycle"
  4: "bus"
  5: "train"
  6: "backpack"
  7: "handbag"
  8: "suitcase"
  9: "wheelchair"
  10: "person_on_wheelchair"
